groups:
- name: main
  jobs:
  - unit-tests
  #- deploy-app
  #- load-tests
  #- promote-new-version

resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: https://github.com/rickeysu/concourse-pipeline-samples.git

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
  - task: run-unit-tests
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/unit-tests.yml
